### PR TITLE
Added support for Dropbox using the Drop-ins plugin and little bit of JS...

### PR DESCRIPTION
**Pull request by ozzieg**
Done
- Added support for Dropbox using Dropbox Drop-ins
- Created Dropbox app to support Drop-in (available for re-use)
- Updated HTML to use Twitter Bootstrap theme
- Added support using Local Storage to remember Dropbox past links
- Updated Device code to use 19200 baud by default to support older Arduinos
  Next
- Improve HTML page look-n-feel

Agent Web Page:
screenshot

Dropbox select:
screenshot

Link Table
screenshot

### CODE REVIEW

**Comment by ozzieg** [comment]
Any consideration on this pull request?

**Comment by nseidle** [comment]
YES! This looks awesome. Thanks for submitting it. I just haven't had a chance to play with it yet.

**Comment by markheloking** [comment]
Any update on merging this request?

**Comment by nseidle** [comment]
This looks really good. Thank you for the updates. I am a little worried about the 19200bps settings on the device side. I believe it will break bootloading for Uno based systems (STK500 is set to 115200 on Unos). Have you had other experience running this at 19200?

**Comment by ozzieg** [comment]
It worked for me consistently without any issues. However, we can always dial it down. No issues with me. 

Thanks,
Ozzie

**Comment by andrewrapp** [comment]
I'm experimenting with porting this to Arduino for the purpose of programming a second Arduino. Any idea if with the lower baud rate it will work with a non-optiboot bootloader? Thanks

**Pull request merged**
